# Generated by Django 4.2.11 on 2025-01-12 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_message_content_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_chat_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_chat_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SimpleChat',
        ),
    ]
