# Generated by Django 4.2.11 on 2025-01-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_conversation_user1_alter_conversation_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
