# Generated by Django 4.2.11 on 2025-01-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_message_recipient_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
